### PR TITLE
Make reversed background adjustable

### PR DESCRIPTION
**Pull request by trmdi**
#11

### CODE REVIEW

**Comment by trmdi** [comment]
Screenshot when using with Breeze plasma theme: 
image

**Comment by psifidotos** [comment]
I think we need to rethough this a bit. As long as we provide such options they can become more generic. The options I think they should look as following:

Background: [  ] Draw separately for each item
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; [  ] Reversed color palette for all items
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;  ----------------------------------- 70% opacity
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;  ----------------------------------- 20% radius

1. First option will be disabled by default
2. First option will enable/disable all subsequent properties
3. Second option we can assume that is always needed with a background so that is why is placed in there
4. By enabling option A, having disabled option B and adjusting option C and D the user can achieve plenty results.

Proposed Defaults:
A: Disabled
B: Enabled, but it will wait for the user to enable A to work
C: 70% or something near that value that does not provide so big solidness
D: 10-20%, something small that plays nice with most plasma themes that do not provide any roundness at all

**Comment by trmdi** [comment]
What will happen in this case?

> 4. By enabling option A, having disabled option B and adjusting option C and D the user can achieve plenty results.

**Comment by trmdi** [comment]
Not sure if it now works as you're expecting. Let's try it.
image

**Comment by psifidotos** [comment]
1. maximum radius should be 100%, in order to achieve that you can use: (Math.min(width,height)/2) * (radius/100)
2. please remove the dots/lines under the sliders they dont look nice

**Comment by trmdi** [comment]
>     1. maximum radius should be 100%, in order to achieve that you can use: (Math.min(width,height)/2) * (radius/100)
> 
>     2. please remove the dots/lines under the sliders they dont look nice

1. I'm not sure. According to this, 50% is the max value: https://www.w3schools.com/howto/howto_css_rounded_images.asp
2. That's because I set stepSize in the Slider.

**Comment by psifidotos** [comment]
1. OK, leave it then I need to update Latte background roundness in that case
2. I suppose it is from your application style in that case and not a general thing

**Comment by trmdi** [comment]
Looks quite nice now. :D

image

**Comment by psifidotos** [comment]
;) nice!
should I merge, is it ready?

**Comment by trmdi** [comment]
> ;) nice!
> should I merge, is it ready?

Yes, I think it's fine enough to merge now.

**Pull request merged**
